Repository NiskuT/Civilization, pull requests merged in 2022-12, with the labels that each got.

#78 feature-11
  .github/workflows/CI.yml
  .github/workflows/develop-pipeline.yml
  .github/workflows/nightly.yml
  .gitignore
  3rdParty/CMakeLists.txt
  3rdParty/dia2code/CMakeLists.txt
  3rdParty/dia2code/src/generate_code_cpp.c
  CMakeLists.txt
  cmake/GenerateDiaHeader.cmake
  include/class-diagram.dia
  ressources/img/map/files.json
  ressources/img/map/player-1.png
  src/client/CMakeLists.txt
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
  src/client/main.cpp
  test/CMakeLists.txt
  test/client/CMakeLists.txt
  test/client/test_texture.cpp
Labels: feature

#90 [feature-14] Add enum class, shared class...
  3rdParty/dia2code/src/dia2code.c
  3rdParty/dia2code/src/dia2code.h
  3rdParty/dia2code/src/generate_code_cpp.c
  3rdParty/dia2code/src/includes.c
  CMakeLists.txt
  include/class-diagram.dia
  src/client/GameWindow.cpp
  src/server/CMakeLists.txt
  src/server/GameEngine.cpp
  src/server/Server.cpp
  src/server/main.cpp
  src/shared/Hexagon.cpp
  src/shared/Map.cpp
  src/shared/PerlinNoise.cpp
  src/shared/Player.cpp
  test/shared/CMakeLists.txt
  test/shared/test_map.cpp
Labels: feature

#89 [improvement-15] Add an offset to the map
  include/class-diagram.dia
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
  test/client/CMakeLists.txt
  test/client/test_texture.cpp
  test/client/test_textureDisplayer.cpp
Labels: improvement

#91 [improvement-12]
  include/class-diagram.dia
  src/client/main.cpp
  src/shared/sayHello.cpp
  test/shared/CMakeLists.txt
  test/shared/test_hello.cpp
Labels: improvement

#92 [feature-16] Add a mooving map and first interractions
  include/class-diagram.dia
  ressources/img/hud/files.json
  ressources/img/hud/font.otf
  ressources/img/hud/priority-card.json
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: feature

#95 [feature-17] Add way to detect which hexagon the player click on
  include/class-diagram.dia
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: feature

#96 [doc-11] Update documentation for release
  README.md
  docs/Doxyfile
  docs/DoxygenLayout.xml
  docs/home-page.md
  docs/rendering.md
  docs/rules/recap-of-specific-actions.md
  src/client/GameWindow.cpp
  test/client/test_textureDisplayer.cpp
Labels: documentation

#97 [feature 13b] Display HUD window
  include/class-diagram.dia
  resources/img/hud/priority-card.json
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: feature
