Repository NiskuT/Civilization, pull requests merged in 2022-10, with the labels that each got.

#2 feature-1: Add README.md
  README.md
Labels: documentation

#4 feature-2: add an mid game map
  ressources/exemple/mapMidGame.json
Labels: feature

#10 [feature-4] Create map graphic elements
  ressources/img/barbarians.png
  ressources/img/field-desert.png
  ressources/img/field-forest.png
  ressources/img/field-grassland.png
  ressources/img/field-hill.png
  ressources/img/field-mountain.png
  ressources/img/field-water.png
  ressources/img/field-wonder-everest.png
  ressources/img/field-wonder-galapagos.png
  ressources/img/field-wonder-kilimanjaro.png
  ressources/img/field-wonder-messa.png
  ressources/img/field-wonder-pantanal.png
  ressources/img/field-wonder-volcanic.png
  ressources/img/player-1-capital.png
  ressources/img/player-1-caravan.png
  ressources/img/player-1-city.png
  ressources/img/player-1-mature.png
  ressources/img/player-1.png
  ressources/img/player-2-capital.png
  ressources/img/player-2-caravan.png
  ressources/img/player-2-city.png
  ressources/img/player-2-mature.png
  ressources/img/player-2.png
  ressources/img/player-3-capital.png
  ressources/img/player-3-caravan.png
  ressources/img/player-3-city.png
  ressources/img/player-3-mature.png
  ressources/img/player-3.png
  ressources/img/player-4-capital.png
  ressources/img/player-4-caravan.png
  ressources/img/player-4-city.png
  ressources/img/player-4-mature.png
  ressources/img/player-4.png
  ressources/img/ressource-antic.png
  ressources/img/ressource-diamond.png
  ressources/img/ressource-oil.png
  ressources/img/ressource-stone.png
  ressources/img/state-city-army.png
  ressources/img/state-city-culture.png
  ressources/img/state-city-industry.png
  ressources/img/state-city-science.png
Labels: feature

#11 [doc-2] add-rules
  Rules/rules.md
Labels: documentation

#22 [improvement-1] Add some images & Change Readme
  README.md
  docs/rules/recap-of-specific-actions.md
  docs/rules/rules.md
  ressources/img/hud/hud.png
  ressources/img/map/barbarian-hutte.png
  ressources/img/map/exemple.png
Labels: improvement

#33 doc-6: change home page
  docs/main.md
Labels: documentation

#32 [Doc 5] Add UML to website
  README.md
  docs/diagram-explanation.md
  docs/res/class-diagram.png
  docs/res/state-diagram.png
  docs/rules/img/state-diagram.png
  docs/state-diagram.dia
  src/state-diagram.dia
Labels: documentation

#35 [BUG-2] Change Diagram explanation link
  README.md
  docs/diagram-explanation.md
Labels: bug

#50 [feature 8]: add test and improve workflow
  .github/workflows/cmake.yml
  .gitignore
  CMakeLists.txt
  test/CMakeLists.txt
  test/client/CMakeLists.txt
  test/client/test_hello.cpp
Labels: feature

#55 feature-9: add valgrind workflow
  .github/workflows/CI.yml
  .github/workflows/develop-pipeline.yml
Labels: feature

#59 [doc-8] Add Install explanation to ReadMe
  README.md
  docs/home-page.md
Labels: documentation

#66 [feature-10] Add clean-headers target for build system
  cmake/GenerateDiaHeader.cmake
Labels: feature
