Repository NiskuT/Civilization, pull requests merged in 2023-01, with the labels that each got.

#105 [improvement-19] add union for dia2code, change name of enum class, an…
  3rdParty/dia2code/src/dia2code.c
  3rdParty/dia2code/src/dia2code.h
  3rdParty/dia2code/src/generate_code_cpp.c
  3rdParty/dia2code/src/includes.c
Labels: improvement

#107 [feature-19] Create action cards HUD
  include/class-diagram.dia
  resources/img/hud/action-card.json
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: feature

#106 [feature-20] Create the clientGameEngine
  include/class-diagram.dia
  resources/img/map/element/barbarian-hutte.png
  resources/img/map/element/barbarians.png
  resources/img/map/element/player-1-capital.png
  resources/img/map/element/player-1-caravan.png
  resources/img/map/element/player-1-city.png
  resources/img/map/element/player-1-mature.png
  resources/img/map/element/player-1-reinforced.png
  resources/img/map/element/player-1.png
  resources/img/map/element/player-2-capital.png
  resources/img/map/element/player-2-caravan.png
  resources/img/map/element/player-2-city.png
  resources/img/map/element/player-2-mature.png
  resources/img/map/element/player-2-reinforced.png
  resources/img/map/element/player-2.png
  resources/img/map/element/player-3-capital.png
  resources/img/map/element/player-3-caravan.png
  resources/img/map/element/player-3-city.png
  resources/img/map/element/player-3-mature.png
  resources/img/map/element/player-3-reinforced.png
  resources/img/map/element/player-3.png
  resources/img/map/element/player-4-capital.png
  resources/img/map/element/player-4-caravan.png
  resources/img/map/element/player-4-city.png
  resources/img/map/element/player-4-mature.png
  resources/img/map/element/player-4-reinforced.png
  resources/img/map/element/player-4.png
  resources/img/map/element/ressource-antic.png
  resources/img/map/element/ressource-diamond.png
  resources/img/map/element/ressource-oil.png
  resources/img/map/element/ressource-stone.png
  resources/img/map/element/state-city-army.png
  resources/img/map/element/state-city-culture.png
  resources/img/map/element/state-city-industry.png
  resources/img/map/element/state-city-science.png
  resources/img/map/field/field-desert.png
  resources/img/map/field/field-forest.png
  resources/img/map/field/field-grassland.png
  resources/img/map/field/field-hill.png
  resources/img/map/field/field-mountain.png
  resources/img/map/field/field-water.png
  resources/img/map/field/field-wonder-everest.png
  resources/img/map/field/field-wonder-galapagos.png
  resources/img/map/field/field-wonder-kilimanjaro.png
  resources/img/map/field/field-wonder-messa.png
  resources/img/map/field/field-wonder-pantanal.png
  resources/img/map/field/field-wonder-volcanic.png
  resources/img/map/files.json
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
  src/client/main.cpp
Labels: feature

#110 [feature-21] Display the playing player
  include/class-diagram.dia
  src/client/GameWindow.cpp
Labels: feature

#113 [improvement-20] Use a jsonfile instead of magic numbers in GameWindow
  resources/img/hud/data-number.json
  src/client/GameWindow.cpp
Labels: improvement

#114 [feature-22] Add a Menu in the starting game
  .github/workflows/CI.yml
  .github/workflows/develop-pipeline.yml
  .github/workflows/nightly.yml
  include/class-diagram.dia
  resources/img/menu/background.png
  resources/img/menu/menu.json
  src/client/Button.cpp
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/MenuWindow.cpp
  src/client/TextureDisplayer.cpp
  src/client/main.cpp
Labels: feature

#118 [feature-18] Address the network part of the game
  .github/workflows/CI.yml
  .github/workflows/develop-pipeline.yml
  .github/workflows/nightly.yml
  3rdParty/dia2code/src/generate_code_cpp.c
  CMakeLists.txt
  include/class-diagram.dia
  src/client/ClientGameEngine.cpp
  src/client/main.cpp
  src/server/GameEngine.cpp
  src/server/Server.cpp
  src/server/main.cpp
  src/shared/Player.cpp
Labels: feature

#120 [feature 23] Move the priority card when clicking on it
  3rdParty/dia2code/src/generate_code_cpp.c
  include/class-diagram.dia
  resources/img/hud/Calibri.ttf
  resources/img/hud/box.png
  resources/img/hud/data-number.json
  resources/img/hud/priority-card.json
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
Labels: feature

#121 [improvement-20] Add event functions and delete some loops to make the code cleaner
  include/class-diagram.dia
  src/client/Button.cpp
  src/client/ClientGameEngine.cpp
  src/client/ClientManager.cpp
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
  src/client/MenuWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: improvement

#127 [improvement-22] remove a level of indentation with using namespace "shared or client or server"
  src/client/Button.cpp
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
  src/client/MenuWindow.cpp
  src/client/TextureDisplayer.cpp
  src/server/GameEngine.cpp
  src/server/Server.cpp
  src/shared/Hexagon.cpp
  src/shared/Map.cpp
  src/shared/PerlinNoise.cpp
  src/shared/Player.cpp
Labels: improvement

#131 [bug-4] specify the folder containing the code to avoid parasites in website class list
  docs/Doxyfile
Labels: bug

#128 [feature 26] Add a validate button on priority cards and move them to the right
  include/class-diagram.dia
  resources/img/hud/data-number.json
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
Labels: feature

#135 [feature-28] Implement the rotation of the tech wheel
  include/class-diagram.dia
  resources/img/hud/arrow.png
  resources/img/hud/files.json
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
  src/client/TextureDisplayer.cpp
Labels: feature

#133 [feature-27] Add chat to the GameWindow
  docs/credits.md
  include/class-diagram.dia
  resources/img/hud/chat-button.png
  resources/img/hud/files.json
  resources/img/hud/leave.png
  resources/img/hud/move-button.png
  src/client/Chat.cpp
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/GraphicCard.cpp
  src/client/MenuWindow.cpp
  src/client/TextureDisplayer.cpp
  src/server/GameEngine.cpp
  src/server/Server.cpp
Labels: feature

#139 [feature-25] Add serialization for objects who need to be shared by server and client
  3rdParty/dia2code/src/generate_code_cpp.c
  include/class-diagram.dia
  src/client/CMakeLists.txt
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
  src/client/main.cpp
  src/server/CMakeLists.txt
  src/server/GameEngine.cpp
  src/server/Server.cpp
  src/shared/Binary.cpp
  src/shared/CMakeLists.txt
  src/shared/Hexagon.cpp
  src/shared/Map.cpp
  src/shared/Player.cpp
  src/shared/Serialization.cpp
  test/CMakeLists.txt
  test/server/CMakeLists.txt
  test/server/test_network.cpp
  test/shared/test_map.cpp
Labels: feature

#143 [feature 15] First version of Rules
  3rdParty/dia2code/src/dia2code.h
  3rdParty/dia2code/src/generate_code_cpp.c
  3rdParty/dia2code/src/scan_tree.c
  include/class-diagram.dia
  src/shared/Barbarian.cpp
  src/shared/BarbarianVillage.cpp
  src/shared/Caravan.cpp
  src/shared/Card.cpp
  src/shared/City.cpp
  src/shared/ControlPawn.cpp
  src/shared/Hexagon.cpp
  src/shared/Player.cpp
  src/shared/Rules.cpp
  test/shared/CMakeLists.txt
  test/shared/test_rules.cpp
Labels: feature

#142 [improvement-24] Add a new function to make clickAction client function more readable
  include/class-diagram.dia
  src/client/GameWindow.cpp
Labels: improvement

#146 [improvement-25] Improve Menu and link between server and client
  include/class-diagram.dia
  resources/font/Calibri.ttf
  resources/font/EnchantedLand.otf
  resources/font/MorrisRomanBlack.otf
  resources/hud/data-number.json
  resources/menu/menu.json
  src/client/Chat.cpp
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/MenuWindow.cpp
  src/server/Server.cpp
Labels: improvement

#148 [feature-29] Add a button to validate the number of boxes played in a round
  include/class-diagram.dia
  resources/hud/data-number.json
  resources/hud/tech-wheel-rotation.json
  resources/validateBoxes/arrow-less.png
  resources/validateBoxes/arrow-more.png
  resources/validateBoxes/dataButton.json
  resources/validateBoxes/done.png
  resources/validateBoxes/little-background.png
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/ValidateBoxesButtons.cpp
Labels: feature

#151 [feature-32] Add a text to specify the actions the user have to do
  include/class-diagram.dia
  resources/hud/data-number.json
  src/client/GameWindow.cpp
  src/client/ValidateBoxesButtons.cpp
Labels: feature

#152 [feature-31] Create Elements when creating the map
  include/class-diagram.dia
  resources/map/element/resource-antic.png
  resources/map/element/resource-diamond.png
  resources/map/element/resource-oil.png
  resources/map/element/resource-stone.png
  resources/map/elementPath.json
  resources/map/resourcePath.json
  resources/map/stateCityPath.json
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/server/GameEngine.cpp
  src/shared/City.cpp
  src/shared/Hexagon.cpp
  src/shared/Map.cpp
  src/shared/Resource.cpp
  src/shared/Serialization.cpp
  test/shared/test_map.cpp
Labels: feature

#159 [bug-7] Bug correction when multiple player are connected
  include/class-diagram.dia
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
Labels: bug

#161 [bug-8] Delete K switch on menu
  src/client/MenuWindow.cpp
Labels: bug

#165 [feature-34] Create an end of round button and a win window
  include/class-diagram.dia
  resources/hud/data-number.json
  resources/pop-up/arrow-less.png
  resources/pop-up/arrow-more.png
  resources/pop-up/dataButton.json
  resources/pop-up/done.png
  resources/pop-up/little-background.png
  src/client/Button.cpp
  src/client/GameWindow.cpp
  src/client/PopUpWindow.cpp
  src/client/ValidateBoxesButtons.cpp
Labels: feature

#166 [improvement-27] Add test for shared elements
  test/shared/CMakeLists.txt
  test/shared/test_barbarian.cpp
  test/shared/test_barbarianvillage.cpp
  test/shared/test_card.cpp
  test/shared/test_city.cpp
  test/shared/test_controlpawn.cpp
  test/shared/test_hexagon.cpp
  test/shared/test_map.cpp
  test/shared/test_resource.cpp
  test/shared/test_serialize.cpp
Labels: improvement

#167 [bug-9] add an atomic to be sure that some class has been initialize correctly
  include/class-diagram.dia
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/shared/City.cpp
  src/shared/Resource.cpp
  src/shared/Serialization.cpp
Labels: bug

#171 [feature-35] Create a function to change the text of the priority card if we change the level
  src/client/GameWindow.cpp
  src/client/MenuWindow.cpp
  src/client/PopUpWindow.cpp
Labels: feature

#172 [improvement-19] Add the good coments on top of the functions for doxygen
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/client/TextureDisplayer.cpp
Labels: improvement

#155 [feature-30] science card Level 1 work
  include/class-diagram.dia
  src/client/ClientGameEngine.cpp
  src/client/GameWindow.cpp
  src/server/GameEngine.cpp
  src/shared/Binary.cpp
  src/shared/Caravan.cpp
  src/shared/Card.cpp
  src/shared/City.cpp
  src/shared/ControlPawn.cpp
  src/shared/Hexagon.cpp
  src/shared/Map.cpp
  src/shared/Player.cpp
  src/shared/Rules.cpp
  src/shared/Serialization.cpp
  test/shared/test_card.cpp
  test/shared/test_city.cpp
  test/shared/test_controlpawn.cpp
  test/shared/test_rules.cpp
  test/shared/test_serialize.cpp
Labels: feature
